fix: fix path to pc-contracts-cli
input-output-hk/partner-chains pull request #219
Opened 2024-11-07 17:00 UTC by tgunnoe

path was broken because the path changed in smart contracts.

# Description

Add your description here, if it fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages.
- [ ] New tests are added if needed and existing tests are updated.
- [ ] Relevant logging and metrics added
- [ ] CI passes. See note on CI.
- [ ] Any changes are noted in the `changelog.md` for affected crate
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG Partner Chains developers to do this
for you.

2024-11-07 21:36 UTC, LGLO requested changes
It still doesn't work. Only nix store hashes are different. It is strange for me, because it still looks into /bin instead of /dist.

```
[Partner Chains Substrate Node Devshell with Smart Contracts CLI]$ pc-contracts-cli --help
/nix/store/rr4hds9brbyvx9z5lyddkfpjisj8f83v-Partner-Chains-Substrate-Node-Devshell-with-Smart-Contracts-CLI-dir/bin/pc-contracts-cli: line 4: /nix/store/v1lwghy0185iybnd78vk7mz6qpd407f5-pc-contracts-cli-bundled/bin/pc-contracts-cli: No such file or directory
```

2024-11-08 10:10 UTC, gilligan submitted a review, later dismissed

2024-11-08 12:43 UTC, tgunnoe commented
Sorry, i missed another path

2024-11-08 14:49 UTC, LGLO approved these changes

2024-11-08 18:06 UTC, merged